### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Riglanto** [Luksack/Automatisation-Test-of-training-site#1]
- [x] Accurate name of repo and desc
- [x] No comments unless necessary
- [x] Extract methods
- [x] Goodbye time.sleep
- [x] Extract test data, xpaths for reusability
- [x] Code formatting, spaces between differenct sections
- [x] Implement PO pattern: http://www.assertselenium.com/automation-design-practices/page-object-pattern/
- step 1 
- step 2
- [x] Order imports
- [x] Read and apply: https://www.python.org/dev/peps/pep-0008/
